name: msds692
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - altair=5.0.1
  - annotated-types=0.6.0
  - anyio=4.7.0
  - aom=3.6.0
  - appdirs=1.4.4
  - appnope=0.1.4
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - attrs=24.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.2
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.528
  - beautifulsoup4=4.13.4
  - blas=1.0
  - blinker=1.9.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.8.3
  - cachetools=5.5.1
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.2.1
  - colorama=0.4.6
  - comm=0.2.3
  - cryptography=44.0.1
  - cssselect=1.3.0
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - fake-useragent=2.2.0
  - fastapi=0.112.2
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - gettext=0.21.0
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.43
  - glog=0.5.0
  - google-api-core=2.24.2
  - google-auth=2.38.0
  - google-cloud-core=2.4.3
  - google-cloud-storage=3.3.0
  - google-crc32c=1.6.0
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.69.2
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libcxx=19.1.7
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.2
  - libgrpc=1.71.0
  - libiconv=1.16
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libxslt=1.1.43
  - llvm-openmp=19.1.7
  - lxml=5.3.0
  - lxml-html-clean=0.4.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - multidict=6.1.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nodejs=20.17.0
  - numexpr=2.11.0
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openjpeg=2.5.2
  - openssl=3.5.2
  - orc=2.1.1
  - packaging=25.0
  - pandas=2.3.1
  - parse=1.20.2
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.46.4
  - platformdirs=4.3.8
  - playwright=1.48.2
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - proto-plus=1.26.1
  - protobuf=5.29.3
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.21
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pyee=13.0.0
  - pygments=2.19.2
  - pyopenssl=25.0.0
  - pypdf=4.2.0
  - pyppeteer=0.0.25
  - pyquery=2.0.1
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyzmq=27.0.1
  - re2=2024.07.02
  - readline=8.3
  - referencing=0.30.2
  - requests=2.32.4
  - requests-html=0.10.0
  - rpds-py=0.22.3
  - rsa=4.7.2
  - setuptools=72.1.0
  - six=1.17.0
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.50.2
  - stack_data=0.6.3
  - starlette=0.38.2
  - streamlit=1.48.0
  - tenacity=9.0.0
  - tk=8.6.15
  - toml=0.10.2
  - toolz=1.0.0
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - w3lib=2.3.1
  - wcwidth=0.2.13
  - websockets=15.0.1
  - wheel=0.45.1
  - xz=5.6.4
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - greenlet==3.2.4
prefix: /opt/homebrew/anaconda3/envs/msds692
